trustify_mass_update:
    # enable only when platform will support it
    # otherwise user won't be able to select field to update and perform actual update
    # MassUpdateController will return 403 in such case
    #
    # Note: Without field level acl it will always "forbidden"
    # default value = false

#    settings:
#        field_acl_enabled: false

    # Name based mapping used to set form type and options to use
    # for rendering updateable field, used only for mass action dialog window
    mapping:
        # For any entity, match by field name only
        all:
            assignedTo:
                type: oro_user_organization_acl_select
                options:
                    label: orocrm.case.caseentity.assigned_to.label

            relatedContact:
                type: orocrm_contact_select
                options:
                    label: orocrm.case.caseentity.related_contact.label

            relatedAccount:
                type: orocrm_account_select
                options:
                    label: orocrm.case.caseentity.related_account.label

#        # Example: Entity - specific mapping
#        OroCRM\Bundle\CaseBundle\Entity\CaseEntity:
#            relatedContact:
#                type: orocrm_contact_select
#                options:
#                    label: orocrm.case.caseentity.related_contact.label
#
